### ISSUE TITLE
[rs_img] Implementirati "zadnji deo" biblioteke u opencv-u

### ISSUE THREAD

**Issue by nkoturovic** [MATF-RS20/RS009-photon#1]
Prednji deo (interfejs) biblioteke je sređen. Ostavljeni su _**TODO**_ markeri u kodu gde je potrebno implementirati određene funkcionalnosti (pomoću opencv biblioteke).

**Lokacije u kodu:**
https://github.com/MATF-RS20/RS009-photon/blob/79869798cccc518241138b4015f771d9f9b6aac4/rs_img/src/display.cpp#L13-L20

https://github.com/MATF-RS20/RS009-photon/blob/79869798cccc518241138b4015f771d9f9b6aac4/rs_img/src/image_impl.cpp#L10-L18

https://github.com/MATF-RS20/RS009-photon/blob/79869798cccc518241138b4015f771d9f9b6aac4/rs_img/src/transform.cpp#L9-L81

**Comment by andrijanacakarevic** [comment]
Odradjeno!
